BOOK_TYPE = (
        ('Erkin', 'Erkin'),
        ('Ijara', 'Ijara')
)

BOOK_QUALITY = (
    ('Yangi', 'Yangi'),
    ("O'rtacha", "O'rtacha"),
    ('Eski', 'Eski')
)

LANGUAGE = (
    ("O'zbek", "O'zbek"),
    ("Ingliz", "Ingliz"),
    ("Rus", "Rus")
)
    
REGION = (
    ('Andijon viloyati', 'Andijon viloyati'),
    ('Buxoro viloyati', 'Buxoro viloyati'),
    ("Farg'ona viloyati", "Farg'ona viloyati"),
    ("Jizzax viloyati", "Jizzax viloyati"),
    ("Xorazm viloyati", "Xorazm viloyati"),
    ("Namangan viloyati", "Namangan viloyati"),
    ("Navoiy viloyati", "Navoiy viloyati"),
    ("Qashqadaryo viloyati", "Qashqadaryo viloyati"),
    ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"),
    ("Samarqand viloyati", "Samarqand viloyati"),
    ("Sirdaryo viloyati", "Sirdaryo viloyati"),
    ("Surxondaryo viloyati", "Surxondaryo viloyati"),
    ("Toshkent viloyati", "Toshkent viloyati")
)
    
CITY = (
    ('Amudaryo tumani', 'Amudaryo tumani'),
    ('Beruniy tumani', 'Beruniy tumani'),
    ('Chimboy tumani', 'Chimboy tumani'),
    ("Ellikqal'a tumani", "Ellikqal'a tumani"),
    ("Kegeyli tumani", "Kegeyli tumani"),
    ("Mo'ynoq tumani", "Mo'ynoq tumani"),
    ("Nukus tumani", "Nukus tumani"),
    ("Qanliko'l tumani", "Qanliko'l tumani"),
    ("Qo'ng'irot tumani", "Qo'ng'irot tumani"),
    ("Qorao'zak tumani", "Qorao'zak tumani"),
    ("Shumanay tumani", "Shumanay tumani"),
    ("Taxtako'pir tumani", "Taxtako'pir tumani"),
    ("To'rtko'l tumani", "To'rtko'l tumani"),
    ("Xo'jayli tumani", "Xo'jayli tumani"),
    ("Taxiatosh tumani", "Taxiatosh tumani"),
    ("Bo'zatov tumani", "Bo'zatov tumani"),
    ("Bog'ot tumani", "Bog'ot tumani"),
    ("Gurlan tumani", "Gurlan tumani"),
    ("Xonqa tumani", "Xonqa tumani"),
    ("Hazorasp tumani", "Hazorasp tumani"),
    ("Xiva tumani", "Xiva tumani"),
    ("Qo'shko'pir tumani", "Qo'shko'pir tumani"),
    ("Shovot tumani", "Shovot tumani"),
    ("Urganch tumani", "Urganch tumani"),
    ("Yangiariq tumani", "Yangiariq tumani"),
    ("Yangibozor tumani", "Yangibozor tumani"),
    ("Tuproqqal'a tumani", "Tuproqqal'a tumani"),
    ("Konimex tumani", "Konimex tumani"),
    ("Karmana tumani", "Karmana tumani"),
    ("Qiziltepa tumani", "Qiziltepa tumani"),
    ("Xatirchi tumani", "Xatirchi tumani"),
    ("Navbahor tumani", "Navbahor tumani"),
    ("Nurota tumani", "Nurota tumani"),
    ("Tomdi tumani", "Tomdi tumani"),
    ("Uchquduq tumani", "Uchquduq tumani"),
    ("Olot tumani", "Olot tumani"),
    ("Buxoro tumani", "Buxoro tumani"),
    ("G'ijduvon tumani", "G'ijduvon tumani"),
    ("Jondor tumani", "Jondor tumani"),
    ("Kogon tumani", "Kogon tumani"),
    ("Qorako'l tumani", "Qorako'l tumani"),
    ("Qorovulbozor tumani", "Qorovulbozor tumani"),
    ("Peshku tumani", "Peshku tumani"),
    ("Romitan tumani", "Romitan tumani"),
    ("Shofirkon tumani", "Shofirkon tumani"),
    ("Vobkent tumani", "Vobkent tumani"),
    ("Bulung'ur tumani", "Bulung'ur tumani"),
    ("Ishtixon tumani", "Ishtixon tumani"),
    ("Jomboy tumani", "Jomboy tumani"),
    ("Kattaqo'rg'on tumani", "Kattaqo'rg'on tumani"),
    ("Qo'shrabot tumani", "Qo'shrabot tumani"), 
    ("Narpay tumani", "Narpay tumani"), 
    ("Nurobod tumani", "Nurobod tumani"),
    ("Oqdaryo tumani", "Oqdaryo tumani"),
    ("Paxtachi tumani", "Paxtachi tumani"),
    ("Payariq tumani", "Payariq tumani"),
    ("Pastdarg'om tumani", "Pastdarg'om tumani"),
    ("Samarqand tumani", "Samarqand tumani"),
    ("Toyloq tumani", "Toyloq tumani"),
    ("Urgut tumani", "Urgut tumani"),
    ("Chiroqchi tumani", "Chiroqchi tumani"),
    ("Dehqonobod tumani", "Dehqonobod tumani"),
    ("G'uzor tumani", "G'uzor tumani"),
    ("Qamashi tumani", "Qamashi tumani"),
    ("Qarshi tumani", "Qarshi tumani"),
    ("Koson tumani", "Koson tumani"),
    ("Kasbi tumani", "Kasbi tumani"),
    ("Kitob tumani", "Kitob tumani"),
    ("Mirishkor tumani", "Mirishkor tumani"),
    ("Muborak tumani", "Muborak tumani"),
    ("Nishon tumani", "Nishon tumani"),
    ("Shahrisabz tumani", "Shahrisabz tumani"),
    ("Yakkabog' tumani", "Yakkabog' tumani"),
    ("Ko'kdala tumani", "Ko'kdala tumani"),
    ("Angor tumani", "Angor tumani"),
    ("Boysun tumani", "Boysun tumani"),
    ("Denov tumani", "Denov tumani"),
    ("Jarqo'rg'on tumani", "Jarqo'rg'on tumani"),
    ("Qiziriq tumani", "Qiziriq tumani"),
    ("Qumqo'rg'on tumani", "Qumqo'rg'on tumani"),
    ("Muzrabot tumani", "Muzrabot tumani"),
    ("Oltinsoy tumani", "Oltinsoy tumani"),
    ("Sariosiyo tumani", "Sariosiyo tumani"),
    ("Sherobod tumani", "Sherobod tumani"),
    ("Sho'rchi tumani", "Sho'rchi tumani"),
    ("Termiz tumani", "Termiz tumani"),
    ("Uzun tumani", "Uzun tumani"), 
    ("Arnasoy tumani", "Arnasoy tumani"),
    ("Baxmal tumani", "Baxmal tumani"),
    ("Do'stlik tumani", "Do'stlik tumani"),
    ("Forish tumani", "Forish tumani"),
    ("G'allaorol tumani", "G'allaorol tumani"),
    ("Sharof Rashidov tumani", "Sharof Rashidov tumani"),
    ("Mirzacho'l tumani", "Mirzacho'l tumani"),
    ("Paxtakor tumani", "Paxtakor tumani"),
    ("Yangiobod tumani", "Yangiobod tumani"),
    ("Zomin tumani", "Zomin tumani"),
    ("Zafarobod tumani", "Zafarobod tumani"),
    ("Zarbdor tumani", "Zarbdor tumani"),
    ("Oqoltin tumani", "Oqoltin tumani"),
    ("Boyovut tumani", "Boyovut tumani"),
    ("Guliston tumani", "Guliston tumani"),
    ("Xovos tumani", "Xovos tumani"),
    ("Mirzaobod tumani", "Mirzaobod tumani"),
    ("Sayxunobod tumani", "Sayxunobod tumani"),
    ("Sardoba tumani", "Sardoba tumani"),
    ("Sirdaryo tumani", "Sirdaryo tumani"),
    ("Yangiyer tumani", "Yangiyer tumani"),
    ("Shirin tumani", "Shirin tumani"),
    ("Guliston tumani", "Guliston tumani"),
    ("Bekobod tumani", "Bekobod tumani"),
    ("Bo'stonliq tumani", "Bo'stonliq tumani"),
    ("Bo'ka tumani", "Bo'ka tumani"),
    ("Chinoz tumani", "Chinoz tumani"),
    ("Qibray tumani", "Qibray tumani"),
    ("Ohangaron tumani", "Ohangaron tumani"),
    ("Oqqo'rg'on tuman", "Oqqo'rg'on tuman"),
    ("Parkent tumani", "Parkent tumani"),
    ("Piskent tumani", "Piskent tumani"),
    ("Quyi Chirchiq tumani", "Quyi Chirchiq tumani"),
    ("O'rta Chirchiq tumani", "O'rta Chirchiq tumani"),
    ("Yangiyo'l tumani", "Yangiyo'l tumani"),
    ("Yuqori Chirchiq tumani", "Yuqori Chirchiq tumani"),
    ("Zangiota tumani", "Zangiota tumani"),
    ("Chortoq tumani", "Chortoq tumani"),
    ("Chust tumani", "Chust tumani"),
    ("Kosonsoy tumani", "Kosonsoy tumani"),
    ("Mingbuloq tumani", "Mingbuloq tumani"),
    ("Namangan tumani", "Namangan tumani"),
    ("Norin tumani", "Norin tumani"), 
    ("Pop tumani", "Pop tumani"),
    ("To'raqo'rg'on tumani", "To'raqo'rg'on tumani"),
    ("Uchqo'rg'on tumani", "Uchqo'rg'on tumani"),
    ("Uychi tumani", "Uychi tumani"),
    ("Yangiqo'rg'on tumani", "Yangiqo'rg'on tumani"),
    ("Oltiariq tumani", "Oltiariq tumani"),
    ("Bag'dod tumani", "Bag'dod tumani"),
    ("Beshariq tumani", "Beshariq tumani"),
    ("Buvayda tumani", "Buvayda tumani"),
    ("Dang'ara tumani", "Dang'ara tumani"),
    ("Farg'ona tumani", "Farg'ona tumani"),
    ("Furqat tumani", "Furqat tumani"),
    ("Qo'shtepa tumani", "Qo'shtepa tumani"),
    ("Quva tumani", "Quva tumani"),
    ("Rishton tumani", "Rishton tumani"),
    ("So'x tumani", "So'x tumani"),
    ("Toshloq tumani", "Toshloq tumani"),
    ("Uchko'prik tumani", "Uchko'prik tumani"),
    ("O'zbekiston tumani", "O'zbekiston tumani"),
    ("Yozyovon tumani", "Yozyovon tumani"),
    ("Quvasoy tumani", "Quvasoy tumani"),
    ("Andijon tumani", "Andijon tumani"),
    ("Asaka tumani", "Asaka tumani"),
    ("Baliqchi tumani", "Baliqchi tumani"),
    ("Bo'z tumani", "Bo'z tumani"),
    ("Buloqboshi tumani", "Buloqboshi tumani"),
    ("Izboskan tumani", "Izboskan tumani"),
    ("Jalaquduq tumani", "Jalaquduq tumani"),
    ("Xo'jaobod tumani", "Xo'jaobod tumani"),
    ("Qo'rg'ontepa tumani", "Qo'rg'ontepa tumani"),
    ("Marhamat tumani", "Marhamat tumani"),
    ("Oltinko'l tumani", "Oltinko'l tumani"),
    ("Paxtaobod tumani", "Paxtaobod tumani"),
    ("Shahrixon tumani", "Shahrixon tumani"),
    ("Ulug'nor tumani", "Ulug'nor tumani"),
    ("Bektemir tumani", "Bektemir tumani"),
    ("Chilonzor tumani", "Chilonzor tumani"),
    ("Hamza tumani", "Hamza tumani"),
    ("Mirobod tumani", "Mirobod tumani"),
    ("Mirzo Ulug'bek tumani", "Mirzo Uug'bek tumani"),
    ("Sergeli tumani", "Sergeli tumani"),
    ("Shayxontohur tumani", "Shayxontohur tumani"),
    ("Olmazor tumani", "Olmazor tumani"),
    ("Uchtepa tumani", "Uchtepa tumani"),
    ("Yakkasaroy tumani", "Yakkasaroy tumani"),
    ("Yunusobod tumani", "Yunusobod tumani"),
    ("Yangihayot tumani", "Yangihayot tumani"),
    ("Toshkent tumani", "Toshkent tumani")
)